added parser for Digitalia Film
ezpaarse-project/ezpaarse-platforms pull request #767
Opened 2023-10-26 16:30 UTC by librarywebchic

2023-10-27 07:50 UTC, oxypomme commented
The analysis is not coherent, as title_id on this platform can be optional, and many analysis have two unitid.

Please review analysis then review parser

2023-10-27 07:54 UTC, oxypomme requested changes
The analysis is not coherent, as title_id on this platform can be optional, and many analysis have two unitid.

Please review analysis then review parser

2023-11-16 10:00 UTC, oxypomme requested changes

2023-11-16 10:00 UTC, oxypomme commented on df/parser.js
> +    result.unitid   = match[3];
Can't find the matching analysis, please review it on analogist.

besides there is maybe too much groups in RegEx

2023-11-23 18:42 UTC, felixleo22 approved these changes

2023-11-23 18:43 UTC, merged